# Generated by Django 4.2.1 on 2023-05-24 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=100)),
                ('client_phone', models.CharField(max_length=100)),
                ('client_address', models.CharField(max_length=100)),
                ('client_country', models.CharField(max_length=100)),
                ('client_city', models.CharField(max_length=100)),
                ('client_zip', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('room_type', models.CharField(max_length=100)),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_status', models.CharField(max_length=100)),
                ('room_image', models.ImageField(upload_to='pics')),
                ('room_description', models.TextField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.client')),
            ],
            options={
                'db_table': 'room',
            },
        ),
    ]
